Caspian Migration
xpring-eng/testnet-faucet pull request #48
Opened 2023-09-01 22:24 UTC by jonathanlei

use Caspian API to ingest data instead of BigQuery, and add network ID as a field for usage tracking beyond testnet

2023-09-06 20:17 UTC, JST5000 commented on src/config.ts
> +  //
Why is this empty comment here?

2023-09-06 20:18 UTC, JST5000 commented on src/config.ts
> +  CASPIAN_SCHEMA_VERSION?: number;
nit: Can you alphabetize these?

2023-09-06 20:19 UTC, JST5000 commented on src/routes/accounts.ts
> +    if (wallet && wallet.seed) {
I thought this was added already, or is this another spot where this double check is required?

2023-09-06 20:20 UTC, JST5000 commented on src/config.ts
>    BIGQUERY_PRIVATE_KEY?: string;
If we're removing the logic for BigQuery, we should also remove these variables.

2023-09-06 20:25 UTC, JST5000 commented on src/routes/accounts.ts
> +        attemptedData: postData, // Here, we include the data that was being sent
nit: I don't think this comment is necessary - I think `attemptedData` conveys this message clearly enough.

2023-09-06 20:26 UTC, JST5000 commented
What did you do to test this PR? (And can you update the `CONTRIBUTING.md` with steps for how they could test their Caspian integration works?)

2023-09-07 18:33 UTC, jonathanlei commented on src/config.ts
>    BIGQUERY_PRIVATE_KEY?: string;
removed

2023-09-07 18:33 UTC, jonathanlei commented on src/routes/accounts.ts
> +    if (wallet && wallet.seed) {
I'm not sure... I thought this was added too

2023-09-07 18:34 UTC, jonathanlei commented on src/config.ts
> +  CASPIAN_SCHEMA_VERSION?: number;
done

2023-09-07 18:34 UTC, JST5000 commented on src/routes/accounts.ts
> +    if (wallet && wallet.seed) {
Maybe they merged to a different branch? (Like how explorer PRs go to `staging`?)

2023-09-07 18:52 UTC, jonathanlei commented
> What did you do to test this PR? (And can you update the `CONTRIBUTING.md` with steps for how they could test their Caspian integration works?)

I manually tested, and it showed up on Caspian table after a triggered workflow run.
adjusted `README.md` and `CONTRIBUTING.md`

2023-09-07 21:49 UTC, JST5000 commented on CONTRIBUTING.md
> +### how to run tests on Standalone Node
nit:
```suggestion
### How to run tests on Standalone Node
```

2023-09-07 21:50 UTC, JST5000 commented on CONTRIBUTING.md
>  Create a folder called config
Please number the rest of the steps

2023-09-07 21:51 UTC, JST5000 commented on CONTRIBUTING.md
> +
Can you add a specific note on how they would test the Caspian integration if they wanted to do that?

2023-09-07 22:03 UTC, ckniffen commented on src/routes/accounts.ts
> -async function insertIntoBigQuery(
We should keep the big query logic, move Caspian and BigQuery methods to the own files with each function accepting the same params.  That will make it easier if we want to add other metric collectors in the future especially for faucets not run by ripple.

2023-09-07 22:04 UTC, ckniffen commented on src/routes/accounts.ts
> +    if (wallet && wallet.seed) {
This code is currently in master. I do not know why the diff is messed up.

2023-09-07 22:12 UTC, ckniffen requested changes

2023-09-07 22:12 UTC, ckniffen commented on src/routes/accounts.ts
> +  console.log(postData);
Remove console.log

2023-09-07 22:12 UTC, ckniffen commented on src/routes/accounts.ts
> +    const req = https.request(
Using something like axios or node-fetch will be simpler here and resolves to a promise already.

2023-09-07 23:19 UTC, jonathanlei commented on CONTRIBUTING.md
> +
I added instructions to add Caspian credentials. not sure what you mean but how they would test, they would need a caspian account and API key which would be granted by Data Engineering ( if the person is from Ripple). Then they would check in the specific table that they provided

2023-09-08 02:10 UTC, jonathanlei commented on src/routes/accounts.ts
> +    const req = https.request(
changed to fetch

2023-09-08 02:13 UTC, jonathanlei commented on src/routes/accounts.ts
> -async function insertIntoBigQuery(
brought the big query logic back

2023-09-12 00:33 UTC, JST5000 commented on src/logging.ts
> +// not in use currently
I generally wouldn't leave a comment like this because it's likely to fall out of date with the code. Instead it might be better to comment at the top of the file something like "Depending on your setup, you can use either Caspian or BigQuery for logging. Other databases may be added in the future."

(That way when someone ends up using the feature, it's still an accurate comment, while still conveying that this isn't dead code, even though it's currently unused)

2023-09-12 00:35 UTC, JST5000 commented on src/routes/accounts.ts
> +      if (config.CASPIAN_API_KEY) {
For the BigQuery logic, this should also try inserting if the BigQuery PROJECT_ID is configured like  it did before. (That way if someone wants to use the BigQuery feature, they just have to change the `.env` file instead of the code)

2023-09-12 00:36 UTC, JST5000 commented on README.md
> -## Google BigQuery Integration
Similarly here, I would include both setups in the README if we're keeping support for both. (Otherwise future users of that feature won't know how to use it)

You may want to add to the "bigger" section a note on how there are multiple setups you can use to log data as a way to group the information.

2023-09-12 00:37 UTC, JST5000 commented on CONTRIBUTING.md
> +
Ok, was curious if there was any nuance to how to setup the test. Like if there's an extra step to trigger the logging logic, or specific information to check in the database to verify that it's working as intended. If not, that's alright :)

2023-09-12 20:12 UTC, jonathanlei commented on CONTRIBUTING.md
> +
I don't think those database logic should be shared publicly :) really depends on individual pipeline's setup.

2023-09-12 22:36 UTC, JST5000 commented on CONTRIBUTING.md
>  Create a folder called config
All these in-between steps should be numbered as well (like "Create a folder called config")

Also, more of a nit for the README in general, but when writing names we should usually use backticks to show it's a `name`. (Specifically, `config` should have the backticks, especially since in the next step we use "config" as a normal word instead of name)

2023-09-12 22:37 UTC, JST5000 commented on src/routes/accounts.ts
> +      if (config.CASPIAN_API_KEY) {
I don't think this has been addressed. If the BigQuery logic is being kept, I think this is important.

2023-09-13 00:47 UTC, JST5000 commented on src/routes/accounts.ts
> +      if (config.CASPIAN_API_KEY) {
Ah, maybe I was viewing an outdated version? Sorry about that then

2023-09-13 00:58 UTC, jonathanlei commented on src/logging.ts
> +// not in use currently
deleted the comment and added Depending on your setup, you can use either Caspian or BigQuery for logging. Other databases may be added in the future.

2023-09-13 00:59 UTC, jonathanlei commented on README.md
> -## Google BigQuery Integration
this is back in the README now and added a title saying we support both

2023-09-22 21:07 UTC, ckniffen approved these changes

2023-09-28 18:21 UTC, JST5000 commented on CONTRIBUTING.md
> +   docker run -p 6006:6006 --interactive -t --volume $PWD/config:/config/ xrpllabsofficial -a --start
This command doesn't work as written, this updated version does though
```suggestion
   docker run -p 6006:6006 --interactive -t --volume $PWD/config:/config/ xrpllabsofficial/xrpld:latest -a --start
```

2023-09-28 18:22 UTC, JST5000 commented on src/logging.ts
> +///Depending on your setup, you can use either Caspian or BigQuery for logging. Other databases may be added in the future
nit:
```suggestion
// Depending on your setup, you can use either Caspian or BigQuery for logging. Other databases may be added in the future
```

2023-09-28 18:23 UTC, JST5000 approved these changes
LGTM after the small docs updates

2024-02-12 22:48 UTC, JST5000 commented on src/logging.ts
> +      throw new Error(`Failed to send data to Caspian: ${errorMessage}`);
```suggestion
      throw new Error(`${errorMessage}`);
```
As written, this will include that message regardless since it will throw an error immediately with your try / catch.

2024-02-13 20:57 UTC, merged