add payment Hash
xpring-eng/testnet-faucet pull request #51
Opened 2023-12-19 23:22 UTC by jonathanlei

High Level Overview of Change
Add Payment Hash to server response and error logging, for better debugging.

Type of Change
[ X] New feature (non-breaking change which adds functionality)

2023-12-20 21:05 UTC, ckniffen requested changes

2023-12-20 21:05 UTC, ckniffen commented on src/routes/accounts.ts
>      try {
Move the signing out of the the `try`.  That way you dont have to create the variable `paymentHash`.

2023-12-20 21:05 UTC, ckniffen commented on src/routes/accounts.ts
>        break;
Add a log statement that if it fails with other types of failures too.

2023-12-20 21:05 UTC, ckniffen commented on src/types.ts
> +  paymentHash: string;
nit: What about `transactionHash`?

2023-12-21 17:10 UTC, JST5000 commented on src/routes/accounts.ts
> +      ({ result, hash: paymentHash } = response);
You can simplify this by ommitting the in-between variable since it's not used elsewhere.
```suggestion
      const { result, hash: paymentHash } = await submitPaymentWithTicket(
        payment,
        client,
        fundingWallet
      );
```

2023-12-21 19:05 UTC, jonathanlei commented on src/routes/accounts.ts
> +      ({ result, hash: paymentHash } = response);
can't do that because result is used outside of the try block

2023-12-21 19:05 UTC, jonathanlei commented on src/types.ts
> +  paymentHash: string;
sure I thought Payment would be more specific

2023-12-21 19:17 UTC, jonathanlei commented on src/routes/accounts.ts
>        break;
the other types of failure are logged in the main function that calls submitPaymentWithTicket

2023-12-21 19:19 UTC, jonathanlei commented on src/routes/accounts.ts
> +      ({ result, hash: paymentHash } = response);
I also would assume that the transactionHash would change after being attached to a ticket? @ckniffen - so the hash would change depends on which stage it errors out, before or after the ticket

2023-12-21 19:33 UTC, ckniffen commented on src/routes/accounts.ts
>        break;
True but this is not descriptive. `    throw new Error("Failed to submit transaction after multiple attempts");`

2023-12-21 22:52 UTC, JST5000 commented on src/routes/accounts.ts
> +      ({ result, hash: paymentHash } = response);
This result can't be used outside the try block as written - there's a separate response instantiated, but `let` has block scoping - so as soon as you're outside these brackets it stops existing.

2024-01-04 19:23 UTC, jonathanlei commented on src/routes/accounts.ts
>      try {
I moved it out, the purpose of having it there is that the hash should be different before and after submitting right? I could have an error statement catching signing errors too.

2024-01-04 19:25 UTC, ckniffen commented on src/routes/accounts.ts
>      try {
The hash will be the same before and after

2024-01-04 19:33 UTC, jonathanlei commented on src/routes/accounts.ts
>      try {
then we don't need signing

2024-01-04 19:36 UTC, ckniffen commented on src/routes/accounts.ts
>      try {
Signing is used to add the signature field but that doesnt change the hash as far as I know.

2024-01-04 19:49 UTC, jonathanlei commented on src/routes/accounts.ts
>        break;
so any other error it would error out to this line:    `${rTracer.id()} | Failed to submit payment ${transactionHash}: ${err}` line 85, and it prints out the error

2024-01-11 23:19 UTC, jonathanlei commented on src/types.ts
> +  paymentHash: string;
changed it to transactionHash

2024-01-12 00:09 UTC, intelliot commented on src/routes/accounts.ts
>      try {
The signature is among the data used to compute a transaction's identifying hash. Adding or changing the signature will change the transaction hash. Relatedly, you can learn about [transaction malleability here](https://xrpl.org/transaction-malleability.html). Generally speaking, I don't consider any given transaction to have a hash yet if it is not signed (yet).

The hash is the same before and after _submitting_, if you are submitting a signed transaction.

2024-01-12 00:12 UTC, intelliot approved these changes
I think this is fine, although I have not tested it. Note that after a transaction is signed, it is possible to compute the transaction's hash. Submitting the transaction doesn't change its hash. So the extra assignment should be unnecessary; though I also don't think it would hurt.

2024-01-22 23:24 UTC, ckniffen approved these changes

2024-01-22 23:28 UTC, merged